-----------------------------------------------
-- PROD_SCN_CODES
-----------------------------------------------
CREATE TABLE VEND_SUBSCRIPTION
(
	SEQUENCE_NUMBER      INTEGER NOT NULL ,
	PROVIDER_GLN         VARCHAR2(13) NOT NULL ,
	PROVIDER_NAME        VARCHAR2(50) NOT NULL ,
	SUBSCRIPTION_STATUS  VARCHAR2(10) NOT NULL ,
	STATUS               VARCHAR2(5) NOT NULL ,
	CREATE_TIME          TIMESTAMP NOT NULL ,
	PROCESS_TIME         TIMESTAMP NULL ,
	CREATE_USER          VARCHAR2(10) NOT NULL ,
	DOCUMENT_ID          VARCHAR2(160) NULL ,
	MESSAGE_ID           VARCHAR2(80) NULL
);

ALTER TABLE VEND_SUBSCRIPTION ADD PRIMARY KEY (SEQUENCE_NUMBER);