INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (0, 'None ', 'None                                              ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (1, 'CPS  ', 'CORE PRODUCT SETUP                                ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (2, 'EXCEL', 'EXCEL BATCH UPLOAD                                ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (3, 'EDI  ', 'EDI 832 PROCESS                                   ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (4, 'PRODM', 'Product Management                                ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (5, 'RTL2 ', 'RTL2                                              ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (6, 'OMI  ', 'OMI                                               ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (7, 'GLDSN', 'GLADSON                                           ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (8, 'VSTCM', 'VESTCOM                                           ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (9, 'GS1  ', 'GS1                                               ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (11, 'IMC  ', 'ItemMaster.Com                                    ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (12, 'KWI  ', 'Kwikee                                            ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (13, 'eCom ', 'eCommerce                                         ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (14, 'Blsm ', 'Blossom                                           ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (15, 'Manu ', 'Manufacturer                                      ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (16, 'Other', 'Other Retailers                                   ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (17, 'SMS  ', 'Scale Management                                  ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (18, 'DAX  ', 'DAX SRM                                           ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (19, 'INSTC', 'Instacart                                         ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (20, 'OBIWA', 'OBIWAN                                            ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (21, 'HEB2U', 'HEB2U                                             ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (22, 'DSV  ', 'Direct Ship Vendor                                ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (491, 'STR  ', 'STORE                                             ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (24, 'SHIPT', 'SHIPT                                             ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (25, 'FPM  ', 'FPM PO CREATION                                   ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (26, 'GNSN ', 'ESHA GENESIS                                      ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (50, 'TEST ', 'SAMPLE                                            ');
INSERT INTO SRC_SYSTEM (SRC_SYSTEM_ID, SRC_SYSTEM_ABB, SRC_SYSTEM_DES) VALUES (51, 'TST1 ', 'SAMPLE                                            ');
